; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[project_options]
;program_name = bldc_test

;program_name = defense_main_exe
;program_name = front_ball_control
;program_name = kicker_test
;program_name = examples/front_ball_control
;program_name = defense_sub_exe
program_name = defense_sub_rcjtw

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_flags = -I include
build_src_filter = +<*.h> +<${project_options.program_name}.cpp>    