; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[project_options]
;program_name = test/motor
;program_name = test/main_esp32
;program_name = test/sub_line
program_name = test/main_lcd
;program_name = test/us
;program_name = sub_exe
[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_flags = -I include
build_src_filter = +<*.h> +<${project_options.program_name}.cpp>    